config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:show, :new , :create] do
  resources :transactions, only: [:new , :create]

  end
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "about", to: "pages#about"
  get "dashboard", to: "pages#dashboard"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :transactions
  validates :title, :category, :price, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactions
  has_many :games
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(games_params)
    @game.user_id = current_user.id

    if @game.save
      redirect_to @game
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def games_params
    params.require(:game).permit(:user_id, :title, :category, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]

  def home
    @games = Game.all
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR category ILIKE :query"
      @games = @games.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def about

  end
  def dashboard

  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_game, only: [:new, :create]

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new
    @transaction.game = @game
    @transaction.user = current_user
    if @transaction.save
      # order was saved
      redirect_to game_path(@game), notice: 'Your order was successfully created!'
    else
      # erro happened while saving the order
      render :new, status: :unprocessable_entity
    end
  end

  def set_game
    @game = Game.find(params[:game_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/new.html.erb
<div class="container w-50 py-5">
<h1> Sell your game  </h1>
<%= simple_form_for @game do |f| %>
  <%= f.input :title %>
  <%= f.input  :category %>
  <%= f.input  :price %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "button-custom"%>
<% end %>
<%= link_to "BACK", root_path%>

</div>

app/views/games/show.html.erb
<div class="container p-5 d-flex justify-content-evenly">
  <div class="d-flex flex-column justify-content-between" style="width: 33%;">
    <div>
      <h1><%= @game.title %></h1>
      <h3>R$ <%= @game.price %></h3>
      <p><%= @game.category %></p>
      <p>Seller: <%= @game.user.name %></p>
    </div>
    <div class="d-flex flex-column">
      <%= link_to "BUY NOW", new_game_transaction_path(@game), class:"button-custom text-center my-3 fw-bold" %>
      <%= link_to "Return to the main page", root_path, class:"text-decoration-underline text-center"%>
    </div>
  </div>
  <% if @game.photo.attached? %>
    <%= cl_image_tag @game.photo.key, class: "d-block product-img" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniteGames</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="site-background">

      <%= render "shared/flashes" %>

      <%= yield %>

    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/_card.html.erb
<div class="games d-flex align-content-start flex-wrap justify-content-evenly pb-5" id="homecards">
  <% @games.each do |game| %>
<div class="card-effect">
    <div class="card-game">
    <% if game.photo.attached? == true %>
      <%= cl_image_tag game.photo.key, class:"card-img-top" %>
    <% else %>
      <img src="https://img.game.co.uk/merch2022/Sony/SonyPScategory-CatM.jpg" class="card-img-top" alt="Game Image"/>

   <% end %>
      <div class="card-game-infos">
        <div>
          <h2><%= game.title %></h2>
          <p><%= game.category %></p>
          <p id="price">R$ <%= game.price %></p>
        </div>
        <%= link_to ">", game_path(game), class: "button-custom" %>
      </div>
    </div>
    </div>
  <% end %>
</div>
   <div class="d-flex justify-content-center"><a href="#"><i class="fas fa-angle-up" id="homeBtn"></i></a></div>

app/views/pages/_carousel.html.erb
<div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner h-75">
    <div class="carousel-item active">
      <%= image_tag 'cs.jpg', class: "d-block w-100"%>
    </div>
    <div class="carousel-item">
      <%= image_tag 'fifa.png', class: "d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slide2.jpg', class: "d-block w-100" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="false"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="false"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/pages/_search_bar.html.erb
  <div class="col-sm-8 my-3">
    <%= form_with url: root_path(anchor: "homecards"), method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Search", name: "", class: "button-custom" %>
    <% end %>
  </div>

app/views/pages/about.html.erb
<div class="d-flex justify-content-center">
  <div class="banner" >
    <div class="container p-5">
      <h1>Unite Games<strong> Expertise em todas as principais plataformas de jogos, incluindo consoles e PCs</strong> para <strong>Comunidade de Jogadores</strong>!</h1><br>
      <p>Bem-vindo ao Unite Games, seu destino número um para todos os jogos! Fundado por três entusiastas de games, Felipe Imbimbo, Guilherme Botelho e Ricardo Rodrigues, nosso objetivo é trazer os melhores e mais recentes jogos para todos os consoles e PC, proporcionando uma experiência de compra única e personalizada. Aqui no Unite Games, entendemos a paixão e o entusiasmo que os jogos podem trazer. Por isso, nos dedicamos a oferecer uma vasta seleção de títulos, desde os lançamentos mais aguardados até os clássicos atemporais. Seja você um fã de jogos de ação, aventura, RPG, esportes ou qualquer outro gênero, temos algo especial para você.</p>
      <p class="mb-4"> Nossa missão é garantir que cada jogador encontre exatamente o que procura, com a conveniência de uma loja online e o suporte de uma equipe que realmente entende de games. Nós nos esforçamos para manter nossos preços competitivos e nosso estoque sempre atualizado, garantindo que você tenha acesso aos melhores jogos no momento em que são lançados. Felipe, Guilherme e Ricardo trouxeram suas visões e experiências únicas para criar uma plataforma onde a comunidade gamer possa se reunir, explorar novos jogos e compartilhar suas paixões. Junte-se a nós nessa jornada épica e descubra seu próximo jogo favorito hoje mesmo!</p>
      <%= link_to "BACK", root_path, class: "button-custom"%>
    </div>
  </div>
<%= image_tag 'dhalsim-01-1280x1024-1.webp', class: "d-block w-50 about-img"%>
</div>

app/views/pages/dashboard.html.erb
<div class="d-flex flex-row">
  <div class="d-flex container py-5 w-50 flex-column text-center">
    <div>
    <% if user_signed_in? %>
        <% if current_user.photo.attached?%>
        <%= cl_image_tag current_user.photo.key, id: "dash-img"%>
        <% else %>
        <%= image_tag "user.jpg", id: "dash-img" %>
        <% end %>
    <% end %>
  </div>

    <h1>Hello, <%= current_user.name %>!</h1>
    <h3>Your sales details:</h3>


    <% total = 0 %>
    <% counter = 0 %>
    <% current_user.transactions.each do |t|%>
    <% total += t.game.price %>
    <% counter += 1 %>
    <% end %>

    <h2>You sold <%= counter %> items</h2>
    <h2>Summing up R$ <%= total %> </h2>

  </div class="d-flex flex-row">
    <div class="d-flex p-5" style="height: 600px; color:white;">
      <div class="vr"></div>
      <div class="vr"></div>
      <div class="vr"></div>
      <div class="vr"></div>
      <div class="vr"></div>
    </div>
    <div>

  <div class="games-bought p-5">
  <h3>The games you sold:</h3>
  <% current_user.transactions.each do |t| %>
  <a href=""><%= cl_image_tag t.game.photo.key, width:"100", height:"75", class:"m-1"%></a>
  <% end %>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<div class="container background_home">

    <%= render "carousel" unless params[:query].present? %>
    <div class="container py-5">
      <div class="row d-flex align-items-center mb-3">
        <div class="col text-left">
          <h2 class="m-0 text-white">Games</h2>
        </div>
        <div class="col d-flex justify-content-end">
          <%= render "search_bar" %>
        </div>
      </div>
      <%= render "card"%>
      
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p class="fw-bold text-black">Made by Unite Games <i class="fas fa-heart"></i></p>
  <div class="footer-links">
    <a href="https://pbs.twimg.com/profile_images/1643667108461412365/9nUoGvqY_400x400.jpg"><i class="fab fa-github"></i></a>
    <a href="https://pbs.twimg.com/profile_images/1643667108461412365/9nUoGvqY_400x400.jpg"><i class="fab fa-instagram"></i></a>
    <a href="https://pbs.twimg.com/profile_images/1643667108461412365/9nUoGvqY_400x400.jpg"><i class="fab fa-facebook"></i></a>
    <a href="https://pbs.twimg.com/profile_images/1643667108461412365/9nUoGvqY_400x400.jpg"><i class="fab fa-twitter"></i></a>
    <a href="https://pbs.twimg.com/profile_images/1643667108461412365/9nUoGvqY_400x400.jpg"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  </div>
  <div class="company mt-3">
    <ul class="list-company">
      Company
      <li><%= link_to "About", about_path ,  class: "link-offset-2 link-underline link-underline-opacity-0 item-list" %></li>
      <li><%= link_to "Team", "https://github.com/unite-games", class: "link-offset-2 link-underline link-underline-opacity-0 item-list" %></li>
    </ul>
  </div>

    <div class="company mt-3">
    <ul class="list-company">
      Community
      <li><%= link_to "Developers", "https://github.com/unite-games", class: "link-offset-2 link-underline link-underline-opacity-0 item-list" %></li>
      <li class="item-list"><%= link_to "Blog", "https://pbs.twimg.com/profile_images/1643667108461412365/9nUoGvqY_400x400.jpg", class: "link-offset-2 link-underline link-underline-opacity-0 item-list" %></li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid fw-bold">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo_navbar_green.png", class: "logo"%> Unite Games

    <% end %>

    <button class="navbar-toggler btn btn-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto fw-bold">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>

        </li>
        <li class="nav-item fw-bold">
        <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>

          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if user_signed_in? %>
                  <% if current_user.photo.attached?%>
                  <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
                  <% else %>
                  <%= image_tag "user.jpg", class: "avatar", alt: "dropdown menu" %>
                  <% end %>
                <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Sell games", new_game_path, class: "dropdown-item" %>
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item d-flex align-items-center">
            <%= link_to "Login", new_user_session_path, class: "button-login" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="d-flex container py-5" style="min-height: 600px;">

<div class="card-details">
<h1>Let's pay</h1>
<h3>To purchase your game please fill the fields below.</h3>
 <div class="d-block">
              <div class="custom-control custom-radio">
                <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
                <label class="custom-control-label" for="credit">Credit card</label>
              </div>
              <div class="custom-control custom-radio">
                <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                <label class="custom-control-label" for="debit">Debit card</label>
              </div>
              <div class="custom-control custom-radio">
                <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                <label class="custom-control-label" for="paypal">Paypal</label>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="cc-name">Name on card</label>
                <input type="text" class="form-control" id="cc-name" placeholder="" required>
                <small class="text-muted">Full name as displayed on card</small>
                <div class="invalid-feedback">
                  Name on card is required
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="cc-number">Credit card number</label>
                <input type="text" class="form-control" id="cc-number" placeholder="" required>
                <div class="invalid-feedback">
                  Credit card number is required
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3 mb-3">
                <label for="cc-expiration">Expiration</label>
                <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
                <div class="invalid-feedback">
                  Expiration date required
                </div>
              </div>
              <div class="col-md-3 mb-3">
                <label for="cc-expiration">CVV</label>
                <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
                <div class="invalid-feedback">
                  Security code required
                </div>
              </div>
            </div>

<%= simple_form_for [@game, @transaction] do |f| %>
  <%= f.button :submit, value: "PAY", class:"button-custom"%>
<% end %>

</div>
<div class="d-flex px-5" style="height: 400px; color:white;">
  <div class="vr"></div>
  <div class="vr"></div>
  <div class="vr"></div>
</div>

<div class="flex-column w-25 py-5">
<div class="flex-row d-flex justify-content-between">
  <p><%= @game.title %></p>
  <p> <%= @game.price %></p>
</div>
<div class="flex-row d-flex justify-content-between">
  <p>Discounts & Offers</p>
  <p>0</p>
</div>
<div class="flex-row d-flex justify-content-between">
  <p>Tax</p>
  <p>0</p>
</div>
  <p>______________________________________</p>
  <p>Total <%= @game.price %></p>
</div>
</div>